<?php

namespace NoteBookBundle\Repository;

/**
 * CardPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
