<?php

namespace NoteBookBundle\Repository;

/**
 * NoteBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteBookRepository extends \Doctrine\ORM\EntityRepository
{
}
